initial commit
droidroot1995/DAFE_Python_015 pull request #1
Opened 2020-10-31 08:45 UTC by laptevaarina

2020-12-10 21:06 UTC, droidroot1995 requested changes
Посмотреть замечания. Поправить.

2020-12-10 21:06 UTC, droidroot1995 commented on Lapteva_Arina/game_life.py
> +
Предлагаю заблочить возможность изменения размеров окна, т.к. при растяжении на полный экран, рабочая зона оказывается в левом верхнем углу. Сделать кнопку очистки поля и полного сброса состояния.

2020-12-10 21:06 UTC, droidroot1995 commented on Lapteva_Arina/game_life.py
> +    sys.exit(app.exec_())
Не хватает кнопки очистки поля.

2020-12-10 21:06 UTC, droidroot1995 commented on Lapteva_Arina/server.py
> +                            print("\nEnd of server")
Нет возможности создать несколько комнат, подписываться/отписываться, покидать комнату и подключаться к ней. Нет уникальных никнеймов.

2020-12-10 21:06 UTC, droidroot1995 commented on Lapteva_Arina/client.py
> +
Лучше выводить список команд при запуске клиента

2020-12-12 06:17 UTC, laptevaarina commented on Lapteva_Arina/game_life.py
> +    sys.exit(app.exec_())
Изменения по игре "Жизнь" добавила в коммите "added correctios"

2020-12-12 06:34 UTC, droidroot1995 approved these changes

2020-12-12 06:59 UTC, merged