first commit
droidroot1995/DAFE_Python_015 pull request #2
Opened 2020-10-31 09:05 UTC by allythe

try 1

2020-12-11 17:39 UTC, droidroot1995 requested changes
Внести правки

2020-12-11 17:39 UTC, droidroot1995 commented on Live_game_NEW
> +    sys.exit(app.exec_())
Удалить. Дублирует файл NEW_LIFE

2020-12-11 17:39 UTC, droidroot1995 commented on Pesotskaya_Alice/Live.py
> +
Удалить. Скатан.

2020-12-11 17:39 UTC, droidroot1995 commented on Pesotskaya_Alice/NEW_LIFE
> +    sys.exit(app.exec_())
Сменить разрешение. Проверить на работоспособность.

2020-12-11 17:39 UTC, droidroot1995 commented on Pesotskaya_Alice/server.py
> +    main()
Скатано.

2020-12-11 17:39 UTC, droidroot1995 commented on Pesotskaya_Alice/client (2).py
> +s.close()
Скатано.

2020-12-11 17:57 UTC, allythe commented on Pesotskaya_Alice/server.py
> +    main()
нет, не списано
изначальный код был взят из видеоурока
доработки делала с фирсовым
списана была жизнь, но ее я переделала

2020-12-11 17:59 UTC, allythe commented on Pesotskaya_Alice/client (2).py
> +s.close()
нет.

2020-12-11 18:12 UTC, allythe commented on Pesotskaya_Alice/NEW_LIFE
> +    sys.exit(app.exec_())
расширение окна?

2020-12-11 19:46 UTC, droidroot1995 commented on Pesotskaya_Alice/NEW_LIFE
> +    sys.exit(app.exec_())
Расширение файла

2020-12-11 19:46 UTC, droidroot1995 commented on Pesotskaya_Alice/client (2).py
> +s.close()
См. здесь https://github.com/droidroot1995/DAFE_Python_015/pull/17

2020-12-11 19:46 UTC, droidroot1995 commented on Pesotskaya_Alice/server.py
> +    main()
См. здесь https://github.com/droidroot1995/DAFE_Python_015/pull/17

2020-12-12 06:10 UTC, droidroot1995 approved these changes

2020-12-12 07:00 UTC, merged