Hw
droidroot1995/DAFE_Python_015 pull request #4
Opened 2020-12-04 20:23 UTC by taurus1605

2020-12-08 15:52 UTC, droidroot1995 requested changes
Удалить из гита папку .idea. Учесть замечания по чату. Поправить GoL, сделать возможность очищать поле, ставить на паузу, останавливать и восстанавливать состояние. Поправить баги

2020-12-08 15:52 UTC, droidroot1995 commented on Arsen_Osipyan/game_of_life/main.py
> +        self.status.showMessage("")
Вот здесь нет необходимости полностью сбрасывать состояние, если игра ставится на паузу, только в случае полной остановки. Потому что, если потом запустить игру, то она работает только по шагам.

2020-12-08 15:52 UTC, droidroot1995 commented on Arsen_Osipyan/game_of_life/main.py
> +                count += 1
Есть смысл зациклить поле, так будет смотреться намного интереснее :)

2020-12-08 15:52 UTC, droidroot1995 commented on Arsen_Osipyan/game_of_life/main.py
> +        self.max_width = 80    # [cells]
Сделать возможность полю быть квадратным при максимальной ширине и высоте.

2020-12-08 15:52 UTC, droidroot1995 commented on Arsen_Osipyan/chat/server.py
> +    server.close()
Сделать возможность завершения сервера по Ctrl+C

2020-12-08 15:52 UTC, droidroot1995 commented on Arsen_Osipyan/chat/client.py
> +    sock.sendto("/".encode("utf-8"), server)
Сделать возможность завершения по Ctrl+C

2020-12-08 22:27 UTC, taurus1605 commented on Arsen_Osipyan/game_of_life/main.py
> +                count += 1
Добавил возможность выбора (зацикленное поле или конечное)

2020-12-11 18:41 UTC, taurus1605 commented on Arsen_Osipyan/game_of_life/main.py
> +        self.max_width = 80    # [cells]
Добавил, до этого исходил из расчета, чтобы весь экран был занят под приложение.

2020-12-11 18:42 UTC, taurus1605 commented on Arsen_Osipyan/chat/server.py
> +    server.close()
Сделал
Реализовал через signal

2020-12-11 18:43 UTC, taurus1605 commented on Arsen_Osipyan/chat/client.py
> +    sock.sendto("/".encode("utf-8"), server)
Сделал
Пришлось немного поменять структуру приложения

2020-12-12 06:45 UTC, droidroot1995 approved these changes

2020-12-12 06:45 UTC, droidroot1995 commented on Arsen_Osipyan/chat/client.py
> +    print()
Отлично

2020-12-12 06:45 UTC, droidroot1995 commented on Arsen_Osipyan/game_of_life/main.py
> +        self.max_width = 80    # [cells]
Можно сделать так, что размер окна будет меняться в зависимости от размера поля :)

2020-12-12 07:14 UTC, merged